name: zioboia
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - cudatoolkit=11.6
  - torchvision
  - pytorch
  - torchaudio
  - pip=23.1.1
  - pip:
      - configargparse
      - ipykernel
      - ipython
      - ipympl
      - pytorch_lightning
      - matplotlib
      - scikit-learn
      - umap
      - biopython
      - pandas
      - pytest
      - numpy
      - pathlib
      - einops
      - wandb
      - -e .
